from __future__ import annotations


SYMBOLS = [
    {
        "symbol": "002594.SZ",
        "market": "A",
        "name": "比亚迪",
        "currency": "CNY",
        "exchange": "SZSE",
        "sector": "新能源",
        "industry": "汽车",
    },
    {
        "symbol": "0700.HK",
        "market": "HK",
        "name": "腾讯控股",
        "currency": "HKD",
        "exchange": "HKEX",
        "sector": "互联网",
        "industry": "平台与游戏",
    },
    {
        "symbol": "NVDA",
        "market": "US",
        "name": "NVIDIA",
        "currency": "USD",
        "exchange": "NASDAQ",
        "sector": "半导体",
        "industry": "AI 算力",
    },
    {
        "symbol": "600519.SH",
        "market": "A",
        "name": "贵州茅台",
        "currency": "CNY",
        "exchange": "SSE",
        "sector": "消费",
        "industry": "白酒",
    },
    {
        "symbol": "688114.SH",
        "market": "A",
        "name": "华大智造",
        "currency": "CNY",
        "exchange": "SSE",
        "sector": "医疗器械",
        "industry": "基因测序设备",
    },
    {
        "symbol": "1810.HK",
        "market": "HK",
        "name": "小米集团",
        "currency": "HKD",
        "exchange": "HKEX",
        "sector": "智能硬件",
        "industry": "手机与汽车",
    },
    {
        "symbol": "AAPL",
        "market": "US",
        "name": "Apple",
        "currency": "USD",
        "exchange": "NASDAQ",
        "sector": "消费电子",
        "industry": "硬件与服务",
    },
]


USERS = [
    {"id": "user-demo", "email": "me@example.local", "display_name": "我的账户"},
    {"id": "user-colleague", "email": "colleague@example.local", "display_name": "同事账户"},
]


ACCOUNTS = [
    {"id": "acct-demo-a", "user_id": "user-demo", "name": "我的主账户", "base_currency": "CNY"},
    {"id": "acct-demo-b", "user_id": "user-colleague", "name": "同事观察账户", "base_currency": "CNY"},
]


DATA_SOURCE_CONFIGS = [
    {
        "id": "cn-akshare-market",
        "market": "A",
        "label": "AKShare A股行情",
        "provider": "akshare",
        "source_kind": "market",
        "requires_key": False,
        "credential_label": "无需 key",
        "enabled": True,
        "configured": True,
    },
    {
        "id": "cn-baostock-history",
        "market": "A",
        "label": "BaoStock 历史日线/回刷",
        "provider": "baostock",
        "source_kind": "market",
        "requires_key": False,
        "credential_label": "无需 key",
        "enabled": True,
        "configured": True,
    },
    {
        "id": "cn-baostock-financial",
        "market": "A",
        "label": "BaoStock 季频财务/公司报告",
        "provider": "baostock-financial",
        "source_kind": "financial",
        "requires_key": False,
        "credential_label": "无需 key",
        "enabled": True,
        "configured": True,
    },
    {
        "id": "cn-tushare-market",
        "market": "A",
        "label": "Tushare Pro A股行情",
        "provider": "tushare",
        "source_kind": "market",
        "requires_key": True,
        "credential_label": "Tushare token",
        "enabled": False,
        "configured": False,
    },
    {
        "id": "cn-tushare-financial",
        "market": "A",
        "label": "Tushare Pro 财务/估值",
        "provider": "tushare",
        "source_kind": "financial",
        "requires_key": True,
        "credential_label": "Tushare token",
        "enabled": False,
        "configured": False,
    },
    {
        "id": "cn-exchange-filings",
        "market": "A",
        "label": "CNINFO / 交易所公告",
        "provider": "cninfo_sse_szse",
        "source_kind": "filing",
        "requires_key": False,
        "credential_label": "无需 key",
        "enabled": True,
        "configured": True,
    },
    {
        "id": "cn-news-sentiment",
        "market": "A",
        "label": "A股新闻情绪",
        "provider": "mock_news_cn",
        "source_kind": "news",
        "requires_key": True,
        "credential_label": "News API key",
        "enabled": False,
        "configured": False,
    },
    {
        "id": "cn-xueqiu-community",
        "market": "A",
        "label": "雪球评论",
        "provider": "xueqiu",
        "source_kind": "news",
        "requires_key": False,
        "credential_label": "Cookie / 浏览器会话",
        "enabled": True,
        "configured": True,
    },
    {
        "id": "hk-market-vendor",
        "market": "HK",
        "label": "港股行情供应商",
        "provider": "mock_hk_market",
        "source_kind": "market",
        "requires_key": True,
        "credential_label": "Market API key",
        "enabled": False,
        "configured": False,
    },
    {
        "id": "hk-financial-provider",
        "market": "HK",
        "label": "港股财务/估值",
        "provider": "mock_hk_financial",
        "source_kind": "financial",
        "requires_key": True,
        "credential_label": "Financial API key",
        "enabled": False,
        "configured": False,
    },
    {
        "id": "hk-finnhub-market",
        "market": "HK",
        "label": "Finnhub 港股行情",
        "provider": "finnhub",
        "source_kind": "market",
        "requires_key": True,
        "credential_label": "Finnhub key",
        "enabled": False,
        "configured": False,
    },
    {
        "id": "hk-finnhub-financial",
        "market": "HK",
        "label": "Finnhub 港股基本面",
        "provider": "finnhub",
        "source_kind": "financial",
        "requires_key": True,
        "credential_label": "Finnhub key",
        "enabled": False,
        "configured": False,
    },
    {
        "id": "hk-hkexnews-filings",
        "market": "HK",
        "label": "HKEXnews 公告",
        "provider": "hkexnews",
        "source_kind": "filing",
        "requires_key": False,
        "credential_label": "无需 key",
        "enabled": True,
        "configured": True,
    },
    {
        "id": "hk-news-sentiment",
        "market": "HK",
        "label": "港股新闻情绪",
        "provider": "mock_news_hk",
        "source_kind": "news",
        "requires_key": True,
        "credential_label": "News API key",
        "enabled": False,
        "configured": False,
    },
    {
        "id": "us-alpha-vantage-market",
        "market": "US",
        "label": "Alpha Vantage 美股行情",
        "provider": "alpha_vantage",
        "source_kind": "market",
        "requires_key": True,
        "credential_label": "Alpha Vantage key",
        "enabled": True,
        "configured": False,
    },
    {
        "id": "us-alpha-vantage-financial",
        "market": "US",
        "label": "Alpha Vantage 基本面",
        "provider": "alpha_vantage",
        "source_kind": "financial",
        "requires_key": True,
        "credential_label": "Alpha Vantage key",
        "enabled": True,
        "configured": False,
    },
    {
        "id": "us-finnhub-market",
        "market": "US",
        "label": "Finnhub 美股行情",
        "provider": "finnhub",
        "source_kind": "market",
        "requires_key": True,
        "credential_label": "Finnhub key",
        "enabled": False,
        "configured": False,
    },
    {
        "id": "us-finnhub-financial",
        "market": "US",
        "label": "Finnhub 基本面",
        "provider": "finnhub",
        "source_kind": "financial",
        "requires_key": True,
        "credential_label": "Finnhub key",
        "enabled": False,
        "configured": False,
    },
    {
        "id": "us-sec-edgar-filings",
        "market": "US",
        "label": "SEC EDGAR 披露",
        "provider": "sec_edgar",
        "source_kind": "filing",
        "requires_key": False,
        "credential_label": "User-Agent",
        "enabled": True,
        "configured": True,
    },
    {
        "id": "us-news-sentiment",
        "market": "US",
        "label": "美股新闻情绪",
        "provider": "mock_news_us",
        "source_kind": "news",
        "requires_key": True,
        "credential_label": "News API key",
        "enabled": False,
        "configured": False,
    },
    {
        "id": "us-alpha-vantage-news",
        "market": "US",
        "label": "Alpha Vantage 新闻情绪",
        "provider": "alpha_vantage",
        "source_kind": "news",
        "requires_key": True,
        "credential_label": "Alpha Vantage key",
        "enabled": True,
        "configured": False,
    },
    {
        "id": "us-finnhub-news",
        "market": "US",
        "label": "Finnhub 公司新闻",
        "provider": "finnhub",
        "source_kind": "news",
        "requires_key": True,
        "credential_label": "Finnhub key",
        "enabled": False,
        "configured": False,
    },
]


FAVORITES = [
    {"account_id": "acct-demo-a", "symbol": "002594.SZ", "note": "新能源核心观察"},
    {"account_id": "acct-demo-a", "symbol": "0700.HK", "note": "港股稳健底仓候选"},
    {"account_id": "acct-demo-a", "symbol": "1810.HK", "note": "催化强但要查证"},
    {"account_id": "acct-demo-b", "symbol": "NVDA", "note": "AI 主线共享分析"},
    {"account_id": "acct-demo-b", "symbol": "AAPL", "note": "等待产品催化"},
]


TRADES = [
    {
        "id": 1,
        "account_id": "acct-demo-a",
        "symbol": "002594.SZ",
        "side": "BUY",
        "trade_date": "2026-05-27",
        "quantity": 300,
        "price": 201.4,
        "fee": 8,
        "currency": "CNY",
    },
    {
        "id": 2,
        "account_id": "acct-demo-a",
        "symbol": "002594.SZ",
        "side": "BUY",
        "trade_date": "2026-06-02",
        "quantity": 200,
        "price": 207.2,
        "fee": 6,
        "currency": "CNY",
    },
    {
        "id": 3,
        "account_id": "acct-demo-a",
        "symbol": "002594.SZ",
        "side": "SELL",
        "trade_date": "2026-06-04",
        "quantity": 100,
        "price": 213.8,
        "fee": 5,
        "currency": "CNY",
    },
    {
        "id": 4,
        "account_id": "acct-demo-a",
        "symbol": "0700.HK",
        "side": "BUY",
        "trade_date": "2026-05-29",
        "quantity": 200,
        "price": 378.4,
        "fee": 12,
        "currency": "HKD",
    },
    {
        "id": 5,
        "account_id": "acct-demo-a",
        "symbol": "NVDA",
        "side": "BUY",
        "trade_date": "2026-05-30",
        "quantity": 60,
        "price": 111.2,
        "fee": 1.2,
        "currency": "USD",
    },
    {
        "id": 6,
        "account_id": "acct-demo-a",
        "symbol": "NVDA",
        "side": "SELL",
        "trade_date": "2026-06-04",
        "quantity": 15,
        "price": 121.8,
        "fee": 1.1,
        "currency": "USD",
    },
    {
        "id": 7,
        "account_id": "acct-demo-b",
        "symbol": "AAPL",
        "side": "BUY",
        "trade_date": "2026-05-28",
        "quantity": 40,
        "price": 198.3,
        "fee": 1.0,
        "currency": "USD",
    },
    {
        "id": 8,
        "account_id": "acct-demo-b",
        "symbol": "600519.SH",
        "side": "BUY",
        "trade_date": "2026-06-03",
        "quantity": 20,
        "price": 1548.0,
        "fee": 5.0,
        "currency": "CNY",
    },
]


ANALYSIS_RUNS = [
    {
        "symbol": "002594.SZ",
        "conclusion": "趋势和催化同时偏强，适合进入观察池并等待成交量确认。",
        "action": "重点观察",
        "confidence": 0.82,
        "input_snapshot_hash": "mock-002594-20260605",
    },
    {
        "symbol": "0700.HK",
        "conclusion": "基本面稳健，短线价格接近压力区，等待回踩更稳。",
        "action": "等待回踩",
        "confidence": 0.78,
        "input_snapshot_hash": "mock-0700-20260605",
    },
    {
        "symbol": "NVDA",
        "conclusion": "基本面和催化强，但估值与波动风险突出，适合持有复核。",
        "action": "持有复核",
        "confidence": 0.80,
        "input_snapshot_hash": "mock-nvda-20260605",
    },
    {
        "symbol": "600519.SH",
        "conclusion": "质量仍强但技术和情绪转弱，持仓需复核核心假设。",
        "action": "减仓观察",
        "confidence": 0.61,
        "input_snapshot_hash": "mock-600519-20260605",
    },
    {
        "symbol": "688114.SH",
        "conclusion": "设备国产化和订单验证是核心变量，当前适合做公告和回款质量复核。",
        "action": "调研观察",
        "confidence": 0.72,
        "input_snapshot_hash": "mock-688114-20260605",
    },
    {
        "symbol": "1810.HK",
        "conclusion": "催化和技术面较强，但未证实信息比例偏高，只保留观察。",
        "action": "重点观察",
        "confidence": 0.76,
        "input_snapshot_hash": "mock-1810-20260605",
    },
    {
        "symbol": "AAPL",
        "conclusion": "质量稳定但短期催化不强，等待财报、产品或回购信息确认。",
        "action": "等待催化",
        "confidence": 0.69,
        "input_snapshot_hash": "mock-aapl-20260605",
    },
]


STOCK_PROFILES = {
    "002594.SZ": {
        "market_label": "A 股",
        "price": 214.36,
        "change": 2.8,
        "action": "重点观察",
        "score": 82,
        "lag_minutes": 1,
        "freshness_status": "fresh",
        "truth_score": 88,
        "factors": {"基本面": 84, "估值": 63, "技术": 79, "催化": 86, "情绪": 74, "风险": 68},
        "spark": [188, 191, 190, 196, 201, 199, 204, 209, 207, 214],
        "thesis": "趋势和催化同时偏强，估值不算便宜，适合进入观察池并等待成交量确认。若真实行情或公告源过期，结论自动降级。",
        "reasons": ["行业景气与订单催化较强", "价格站上关键均线，成交额同步放大", "估值处于中性偏高区间"],
        "risks": ["估值容错较低", "行业政策和价格战会放大波动"],
        "metrics": {
            "avg_amount_cny": 12800000000,
            "turnover_rate": 2.1,
            "spread_bps": 4,
            "pe": 24.8,
            "pe_percentile": 68,
            "pb": 4.2,
            "roe": 18.6,
            "revenue_growth": 21.4,
            "fcf_margin": 6.1,
            "debt_ratio": 52,
            "volume_ratio": 1.48,
            "ma20_gap_pct": 5.6,
            "atr_pct": 3.2,
            "catalyst_score": 86,
            "news_count_72h": 18,
            "verified_catalyst_ratio": 0.78,
            "sentiment_score": 42,
            "unverified_ratio": 0.19,
            "volatility_20d": 28,
            "max_drawdown_60d": 12,
        },
        "evidence": [
            {"tier": "S", "source": "交易所公告 Mock", "claim": "近期公告未发现停牌或重大风险提示", "confidence": 0.93},
            {"tier": "A", "source": "财务数据 Mock", "claim": "收入和现金流质量维持正向", "confidence": 0.84},
            {"tier": "B", "source": "新闻情绪 Mock", "claim": "行业订单和出口话题热度上升", "confidence": 0.72},
        ],
        "reflection": [
            {"round": "第 1 轮", "label": "数据闸门", "status": "pass", "text": "行情延迟 1 分钟，财务和公告字段完整，可继续分析。"},
            {"round": "第 2 轮", "label": "证据闸门", "status": "pass", "text": "主要 claim 有公告或结构化财务支撑，情绪仅作辅助。"},
            {"round": "第 3 轮", "label": "投资逻辑", "status": "warn", "text": "逻辑成立但估值偏高，动作从小仓试探降级为重点观察。"},
        ],
    },
    "0700.HK": {
        "market_label": "港股",
        "price": 391.8,
        "change": 1.4,
        "action": "等待回踩",
        "score": 78,
        "lag_minutes": 8,
        "freshness_status": "fresh",
        "truth_score": 84,
        "factors": {"基本面": 86, "估值": 70, "技术": 67, "催化": 72, "情绪": 76, "风险": 74},
        "spark": [370, 374, 377, 381, 386, 383, 388, 392, 389, 391],
        "thesis": "基本面稳健，短线价格已接近压力区，当前更适合等待回踩或业绩催化确认。",
        "reasons": ["盈利质量和现金流稳定", "回购与业务韧性支持估值", "短线技术位置不够从容"],
        "risks": ["监管和平台经济政策扰动", "港股流动性和汇率波动"],
        "metrics": {
            "avg_amount_cny": 9600000000,
            "turnover_rate": 0.62,
            "spread_bps": 5,
            "pe": 18.7,
            "pe_percentile": 54,
            "pb": 3.8,
            "roe": 20.4,
            "revenue_growth": 9.8,
            "fcf_margin": 18.2,
            "debt_ratio": 38,
            "volume_ratio": 1.08,
            "ma20_gap_pct": 2.4,
            "atr_pct": 2.6,
            "catalyst_score": 72,
            "news_count_72h": 23,
            "verified_catalyst_ratio": 0.81,
            "sentiment_score": 36,
            "unverified_ratio": 0.16,
            "volatility_20d": 21,
            "max_drawdown_60d": 9,
        },
        "evidence": [
            {"tier": "S", "source": "HKEXnews Mock", "claim": "公告源可追溯，未发现冲突信息", "confidence": 0.91},
            {"tier": "A", "source": "公司财务 Mock", "claim": "利润率稳定，现金流良好", "confidence": 0.82},
            {"tier": "B", "source": "财经新闻 Mock", "claim": "回购和 AI 业务话题带动情绪", "confidence": 0.68},
        ],
        "reflection": [
            {"round": "第 1 轮", "label": "数据闸门", "status": "pass", "text": "港股 mock 行情延迟 8 分钟，仍在本原型阈值内。"},
            {"round": "第 2 轮", "label": "证据闸门", "status": "pass", "text": "公司动作以 HKEXnews Mock 为核心证据，新闻未单独触发结论。"},
            {"round": "第 3 轮", "label": "投资逻辑", "status": "warn", "text": "基本面支持持有观察，但技术面追价性价比不足。"},
        ],
    },
    "NVDA": {
        "market_label": "美股",
        "price": 118.64,
        "change": -0.9,
        "action": "持有复核",
        "score": 80,
        "lag_minutes": 18,
        "freshness_status": "warn",
        "truth_score": 81,
        "factors": {"基本面": 91, "估值": 48, "技术": 73, "催化": 88, "情绪": 82, "风险": 54},
        "spark": [104, 109, 113, 117, 121, 119, 123, 126, 120, 118],
        "thesis": "基本面和催化很强，但估值与波动风险同样突出。若用于建仓，必须有仓位上限和失效条件。",
        "reasons": ["AI 算力需求仍是强催化", "估值分位较高，安全边际不足", "短期波动放大，需要等待确认"],
        "risks": ["高估值回撤", "供应链和出口限制", "预期过热"],
        "metrics": {
            "avg_amount_cny": 196000000000,
            "turnover_rate": 1.35,
            "spread_bps": 2,
            "pe": 39.6,
            "pe_percentile": 91,
            "pb": 26.4,
            "roe": 72.8,
            "revenue_growth": 78.1,
            "fcf_margin": 33.5,
            "debt_ratio": 19,
            "volume_ratio": 1.31,
            "ma20_gap_pct": 4.2,
            "atr_pct": 4.8,
            "catalyst_score": 88,
            "news_count_72h": 41,
            "verified_catalyst_ratio": 0.74,
            "sentiment_score": 55,
            "unverified_ratio": 0.23,
            "volatility_20d": 42,
            "max_drawdown_60d": 17,
        },
        "evidence": [
            {"tier": "S", "source": "SEC EDGAR Mock", "claim": "财报字段完整，可核验收入和利润", "confidence": 0.9},
            {"tier": "A", "source": "结构化基本面 Mock", "claim": "增长和毛利率维持高位", "confidence": 0.86},
            {"tier": "B", "source": "新闻情绪 Mock", "claim": "AI 芯片需求叙事仍强", "confidence": 0.7},
        ],
        "reflection": [
            {"round": "第 1 轮", "label": "数据闸门", "status": "warn", "text": "美股当前按上一交易日数据分析，盘前/盘中需要刷新。"},
            {"round": "第 2 轮", "label": "证据闸门", "status": "pass", "text": "核心财务 claim 来自 SEC Mock，新闻情绪只做辅助。"},
            {"round": "第 3 轮", "label": "投资逻辑", "status": "warn", "text": "强趋势与高估值并存，动作保留为持有复核。"},
        ],
    },
    "600519.SH": {
        "market_label": "A 股",
        "price": 1518.2,
        "change": -1.7,
        "action": "减仓观察",
        "score": 61,
        "lag_minutes": 2,
        "freshness_status": "fresh",
        "truth_score": 79,
        "factors": {"基本面": 82, "估值": 55, "技术": 42, "催化": 46, "情绪": 38, "风险": 62},
        "spark": [1620, 1608, 1599, 1570, 1556, 1562, 1540, 1531, 1522, 1518],
        "thesis": "基本面质量仍强，但技术面和情绪转弱，若已持有应复核核心假设和仓位暴露。",
        "reasons": ["盈利质量仍有支撑", "趋势弱化，缺少短期催化", "消费预期和估值分歧扩大"],
        "risks": ["需求预期下修", "高股价流动性影响仓位管理"],
        "metrics": {
            "avg_amount_cny": 7600000000,
            "turnover_rate": 0.28,
            "spread_bps": 6,
            "pe": 22.1,
            "pe_percentile": 57,
            "pb": 8.8,
            "roe": 31.6,
            "revenue_growth": 13.7,
            "fcf_margin": 29.1,
            "debt_ratio": 17,
            "volume_ratio": 0.86,
            "ma20_gap_pct": -4.9,
            "atr_pct": 2.1,
            "catalyst_score": 46,
            "news_count_72h": 12,
            "verified_catalyst_ratio": 0.68,
            "sentiment_score": -22,
            "unverified_ratio": 0.26,
            "volatility_20d": 18,
            "max_drawdown_60d": 14,
        },
        "evidence": [
            {"tier": "S", "source": "交易所公告 Mock", "claim": "公告源未出现硬性利空", "confidence": 0.88},
            {"tier": "A", "source": "财务数据 Mock", "claim": "盈利质量仍高", "confidence": 0.8},
            {"tier": "B", "source": "情绪数据 Mock", "claim": "消费板块情绪偏弱", "confidence": 0.62},
        ],
        "reflection": [
            {"round": "第 1 轮", "label": "数据闸门", "status": "pass", "text": "关键行情和财务字段可用。"},
            {"round": "第 2 轮", "label": "证据闸门", "status": "warn", "text": "负面情绪主要来自新闻和价格行为，未见公告级别硬利空。"},
            {"round": "第 3 轮", "label": "投资逻辑", "status": "warn", "text": "卖出理由不能只靠短线下跌，建议减仓观察而非直接退出。"},
        ],
    },
    "688114.SH": {
        "market_label": "A 股",
        "price": 82.6,
        "change": 1.9,
        "action": "调研观察",
        "score": 72,
        "lag_minutes": 3,
        "freshness_status": "fresh",
        "truth_score": 82,
        "factors": {"基本面": 68, "估值": 58, "技术": 71, "催化": 79, "情绪": 66, "风险": 63},
        "spark": [73, 74.5, 76.2, 75.4, 78.6, 80.1, 79.4, 81.2, 80.8, 82.6],
        "thesis": "生命科学工具链国产替代具备调研价值，但需要持续复核订单兑现、毛利率和回款质量。",
        "reasons": ["公告和股东会材料较多，适合做事件回溯", "国产测序平台和海外渠道是关键催化", "盈利质量仍需要结合财报和现金流验证"],
        "risks": ["研发投入和商业化节奏可能影响利润", "高端设备需求波动会放大估值分歧"],
        "metrics": {
            "avg_amount_cny": 1850000000,
            "turnover_rate": 1.18,
            "spread_bps": 6,
            "pe": 42.5,
            "pe_percentile": 71,
            "pb": 3.4,
            "roe": 6.8,
            "revenue_growth": 16.5,
            "fcf_margin": 2.4,
            "debt_ratio": 34,
            "volume_ratio": 1.24,
            "ma20_gap_pct": 3.1,
            "atr_pct": 4.1,
            "catalyst_score": 79,
            "news_count_72h": 10,
            "verified_catalyst_ratio": 0.72,
            "sentiment_score": 24,
            "unverified_ratio": 0.21,
            "volatility_20d": 31,
            "max_drawdown_60d": 15,
        },
        "evidence": [
            {"tier": "S", "source": "SSE 上交所公告 Mock", "claim": "近期可检索到股东会、回购和诉讼相关公告，适合做公告链复核。", "confidence": 0.88},
            {"tier": "A", "source": "财务数据 Mock", "claim": "收入增长具备弹性，但现金流和毛利率需要逐季验证。", "confidence": 0.78},
            {"tier": "B", "source": "行业新闻 Mock", "claim": "生命科学工具和国产替代话题保持关注度。", "confidence": 0.66},
        ],
        "reflection": [
            {"round": "第 1 轮", "label": "数据闸门", "status": "pass", "text": "A 股 mock 行情和公告字段可用于原型演示。"},
            {"round": "第 2 轮", "label": "证据闸门", "status": "warn", "text": "催化以公告和行业信息为主，真实版本需要核对订单、回款和诉讼细节。"},
            {"round": "第 3 轮", "label": "投资逻辑", "status": "warn", "text": "先定为调研观察，不直接升级为交易动作。"},
        ],
    },
    "1810.HK": {
        "market_label": "港股",
        "price": 29.72,
        "change": 3.1,
        "action": "重点观察",
        "score": 76,
        "lag_minutes": 22,
        "freshness_status": "warn",
        "truth_score": 73,
        "factors": {"基本面": 70, "估值": 66, "技术": 81, "催化": 82, "情绪": 79, "风险": 57},
        "spark": [24, 25, 25.7, 26.5, 27.4, 26.8, 28.1, 28.9, 29.2, 29.7],
        "thesis": "催化和技术面较强，但部分情绪来自市场传闻，真实版本必须用公告和销量数据核验。",
        "reasons": ["智能硬件和汽车业务催化明显", "趋势强于港股大盘", "情绪热度高但未证实比例偏高"],
        "risks": ["新业务估值波动", "传闻驱动导致追高风险"],
        "metrics": {
            "avg_amount_cny": 18200000000,
            "turnover_rate": 2.85,
            "spread_bps": 7,
            "pe": 27.5,
            "pe_percentile": 63,
            "pb": 3.6,
            "roe": 12.9,
            "revenue_growth": 17.2,
            "fcf_margin": 4.8,
            "debt_ratio": 48,
            "volume_ratio": 1.76,
            "ma20_gap_pct": 8.1,
            "atr_pct": 5.4,
            "catalyst_score": 82,
            "news_count_72h": 35,
            "verified_catalyst_ratio": 0.52,
            "sentiment_score": 49,
            "unverified_ratio": 0.41,
            "volatility_20d": 46,
            "max_drawdown_60d": 21,
        },
        "evidence": [
            {"tier": "S", "source": "HKEXnews Mock", "claim": "公告字段可追溯", "confidence": 0.86},
            {"tier": "B", "source": "新闻情绪 Mock", "claim": "汽车业务话题热度上升", "confidence": 0.66},
            {"tier": "C", "source": "社媒热度 Mock", "claim": "短线讨论度快速上升", "confidence": 0.38},
        ],
        "reflection": [
            {"round": "第 1 轮", "label": "数据闸门", "status": "warn", "text": "行情延迟 22 分钟，接近原型阈值上限。"},
            {"round": "第 2 轮", "label": "证据闸门", "status": "warn", "text": "催化中有传闻成分，未证实比例偏高。"},
            {"round": "第 3 轮", "label": "投资逻辑", "status": "warn", "text": "保留观察，不升级为买入候选。"},
        ],
    },
    "AAPL": {
        "market_label": "美股",
        "price": 203.44,
        "change": 0.4,
        "action": "等待催化",
        "score": 69,
        "lag_minutes": 20,
        "freshness_status": "warn",
        "truth_score": 83,
        "factors": {"基本面": 78, "估值": 58, "技术": 62, "催化": 55, "情绪": 64, "风险": 75},
        "spark": [197, 199, 198, 201, 203, 204, 202, 205, 204, 203],
        "thesis": "质量稳定但短期催化不强，适合放在关注池等待财报、产品或回购信息确认。",
        "reasons": ["现金流和回购能力强", "增长催化不够清晰", "风险相对可控"],
        "risks": ["估值和增长匹配度", "新品周期不确定"],
        "metrics": {
            "avg_amount_cny": 82000000000,
            "turnover_rate": 0.74,
            "spread_bps": 2,
            "pe": 29.4,
            "pe_percentile": 72,
            "pb": 38.1,
            "roe": 151.2,
            "revenue_growth": 4.8,
            "fcf_margin": 23.7,
            "debt_ratio": 56,
            "volume_ratio": 0.96,
            "ma20_gap_pct": 1.3,
            "atr_pct": 2.4,
            "catalyst_score": 55,
            "news_count_72h": 28,
            "verified_catalyst_ratio": 0.72,
            "sentiment_score": 18,
            "unverified_ratio": 0.14,
            "volatility_20d": 17,
            "max_drawdown_60d": 8,
        },
        "evidence": [
            {"tier": "S", "source": "SEC EDGAR Mock", "claim": "财务披露完整", "confidence": 0.9},
            {"tier": "A", "source": "公司 IR Mock", "claim": "回购和现金流可核验", "confidence": 0.82},
            {"tier": "B", "source": "新闻情绪 Mock", "claim": "产品周期讨论度中性", "confidence": 0.64},
        ],
        "reflection": [
            {"round": "第 1 轮", "label": "数据闸门", "status": "warn", "text": "美股按上一交易日数据，盘中需刷新。"},
            {"round": "第 2 轮", "label": "证据闸门", "status": "pass", "text": "财务和回购 claim 有较高等级证据。"},
            {"round": "第 3 轮", "label": "投资逻辑", "status": "pass", "text": "结论与证据匹配：等待催化，暂不追高。"},
        ],
    },
}


MEMORIES = [
    {
        "symbol": item["symbol"],
        "memory_version": "mock-v1",
        "reusable_json": {
            "entity": item["symbol"],
            "shared_with_accounts": True,
            "baseline": "公司画像、交易所代码、币种、行业标签和上次分析结论可复用。",
        },
        "must_refresh_json": {
            "market": "行情、K线、成交额、买卖价差必须重新拉取。",
            "news": "新公告和新闻情绪必须重新计算。",
        },
        "invalidated_by": ["new_filing", "large_price_move", "provider_conflict", "model_version_change"],
    }
    for item in SYMBOLS
]
